import React from "react";
export type GatewaySessionStatusTone = "ok" | "warn" | "err";
export type GatewaySessionSignInCardProps = {
    kicker?: string;
    title?: string;
    description?: React.ReactNode;
    statusLabel?: string;
    statusTone?: GatewaySessionStatusTone;
    tokenSourceLabel?: string;
    showGatewayUrl?: boolean;
    gatewayUrl?: string;
    gatewayUrlPlaceholder?: string;
    onGatewayUrlChange?: (value: string) => void;
    userId: string;
    userPlaceholder?: string;
    onUserIdChange: (value: string) => void;
    token: string;
    tokenPlaceholder?: string;
    showToken?: boolean;
    onTokenChange: (value: string) => void;
    onShowTokenChange?: (value: boolean) => void;
    remember?: boolean;
    rememberLabel?: string;
    onRememberChange?: (value: boolean) => void;
    loading?: boolean;
    submitting?: boolean;
    submitDisabled?: boolean;
    submitLabel?: string;
    submittingLabel?: string;
    closeLabel?: string;
    signOutLabel?: string;
    showClose?: boolean;
    showSignOut?: boolean;
    error?: string;
    /** Success/info notice rendered where errors render (e.g. "Signed out."). */
    message?: string;
    className?: string;
    onSubmit: () => void | Promise<void>;
    onClose?: () => void;
    onSignOut?: () => void | Promise<void>;
};
export declare function GatewaySessionSignInCard({ kicker, title, description, statusLabel, statusTone, tokenSourceLabel, showGatewayUrl, gatewayUrl, gatewayUrlPlaceholder, onGatewayUrlChange, userId, userPlaceholder, onUserIdChange, token, tokenPlaceholder, showToken, onTokenChange, onShowTokenChange, remember, rememberLabel, onRememberChange, loading, submitting, submitDisabled, submitLabel, submittingLabel, closeLabel, signOutLabel, showClose, showSignOut, error, message, className, onSubmit, onClose, onSignOut, }: GatewaySessionSignInCardProps): React.ReactElement;
//# sourceMappingURL=gateway_session_signin.d.ts.map