#!/usr/bin/env node
// The shared route pickers' host props (round 3, entity Mind/Voice + console
// Manage): `inheritLabel` names the inherit choice in the reasoning and MTP
// selects; `optionsInDefaultMode: false` takes the gateway default whole
// (no reasoning/MTP until a custom provider/model is chosen); VoiceSettings
// `intro` / `delivery` / `showReset` / `defaultHint` / `voiceDefaultLabel`.
// Each assertion fails when its prop is removed.
import assert from "node:assert/strict";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { ProviderModelPicker } from "../dist/provider_model_picker.js";
import { VoiceSettings } from "../dist/voice_settings.js";

const h = React.createElement;
const none = async () => [];
const base = {
  onChange: () => {},
  fetchProviders: none,
  fetchModels: none,
  fetchModelCapabilities: async () => ({}),
  enableSpeculation: true,
};

// Defaults unchanged: on Gateway default the MTP select shows with the
// workflow-aware inherit label (Code / Assistant behaviour).
const legacy = renderToStaticMarkup(h(ProviderModelPicker, { ...base, value: { provider: "", model: "", reasoning: "low" } }));
assert.match(legacy, /MTP depth/);
assert.match(legacy, /Workflow \/ Gateway default/);

// inheritLabel replaces the inherit choice in both selects.
const entityCustom = renderToStaticMarkup(h(ProviderModelPicker, {
  ...base, inheritLabel: "Gateway default", optionsInDefaultMode: false,
  value: { provider: "lmstudio", model: "m", reasoning: "low" },
}));
assert.match(entityCustom, /MTP depth/);
assert.match(entityCustom, /Reasoning effort/);
assert.doesNotMatch(entityCustom, /Workflow \/ Gateway default/);

// optionsInDefaultMode: false hides reasoning + MTP while on the gateway default.
const entityDefault = renderToStaticMarkup(h(ProviderModelPicker, {
  ...base, inheritLabel: "Gateway default", optionsInDefaultMode: false,
  defaultHint: "Gateway default: lmstudio · route-model.",
  value: { provider: "", model: "", reasoning: "low" },
}));
assert.doesNotMatch(entityDefault, /MTP depth/);
assert.doesNotMatch(entityDefault, /Reasoning effort/);
assert.match(entityDefault, /Gateway default: lmstudio · route-model\./);
assert.match(entityDefault, /aria-selected="true"[^>]*>Gateway default</);

// VoiceSettings host props.
const fetchCatalog = async () => ({});
const voiceLegacy = renderToStaticMarkup(h(VoiceSettings, { value: {}, onChange: () => {}, fetchCatalog }));
assert.match(voiceLegacy, /Speech is generated by your authenticated Gateway/);
assert.match(voiceLegacy, /Speaking speed/);
assert.match(voiceLegacy, /Reset to Gateway defaults/);
const voiceEntity = renderToStaticMarkup(h(VoiceSettings, {
  value: {}, onChange: () => {}, fetchCatalog,
  intro: null, delivery: false, showReset: false,
  defaultHint: "Gateway default: supertonic · F1.",
  voiceDefaultLabel: "Gateway default voice",
}));
assert.doesNotMatch(voiceEntity, /Speech is generated/);
assert.doesNotMatch(voiceEntity, /Speaking speed/);
assert.doesNotMatch(voiceEntity, /Reset to Gateway defaults/);
assert.match(voiceEntity, /Gateway default: supertonic · F1\./);
assert.match(voiceEntity, /Gateway default voice/);
console.log("check_route_picker: OK");
