import assert from 'node:assert/strict';
import { speculationCapability, normalizeSpeculationValue, speculationFromSelection, speculationSelection } from '../dist/speculation_control.js';
import { SpeculationSelect } from '../dist/speculation_select.js';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
assert.equal(normalizeSpeculationValue(false), false);
assert.equal(normalizeSpeculationValue({mode:'off'}), false);
assert.equal(speculationFromSelection(''), undefined);
assert.equal(speculationSelection(false), 'off');
assert.deepEqual(speculationFromSelection('3'), {mode:'native_mtp',num_draft_tokens:3,require_acceleration:true});
for (const value of [true, 'native_mtp', {mode:'native_mtp',num_draft_tokens:true}, {mode:'native_mtp',num_draft_tokens:2.5}]) assert.equal(normalizeSpeculationValue(value), undefined);
assert.equal(speculationCapability({capabilities:{speculation:{native_mtp:true}}}), null);
const payload = {execution:{speculation:{supported:true,ready:false,reason:'head_not_loaded',supported_depths:[2,3,4,5,true,2.5,2],default:{mode:'native_mtp',num_draft_tokens:2},requires_reload:true}}};
assert.deepEqual(speculationCapability(payload).supported_depths, [2,3,4,5]);
const markup = renderToStaticMarkup(React.createElement(SpeculationSelect, {capabilities:payload,onChange:()=>{}}));
assert.match(markup, /depth 2/);
assert.match(markup, /head_not_loaded/);
const unknown = renderToStaticMarkup(React.createElement(SpeculationSelect, {onChange:()=>{}}));
assert.match(unknown, /capability unknown/);
assert.doesNotMatch(unknown, /Depth [2345]/);
console.log('speculation controls: passed');
