import React, { useEffect, useRef, useState } from "react";
import { AfSelect } from "./af_select.js";
import { ProviderModelPicker } from "./provider_model_picker.js";

export type VoicePreferences = {
  provider?: string;
  model?: string;
  voice?: string;
  profile?: string;
  speed?: number;
  quality_preset?: string;
  instructions?: string;
};
export type VoiceCatalog = Record<string, any>;
const names = (value: unknown): string[] =>
  Array.isArray(value)
    ? value
        .map((item) =>
          typeof item === "string" ? item : item?.id || item?.name,
        )
        .filter(Boolean)
    : [];

/** Gateway-catalog driven and transport injected, usable in any chat host. */
export function VoiceSettings({
  value,
  onChange,
  fetchCatalog,
}: {
  value: VoicePreferences;
  onChange: (value: VoicePreferences) => void;
  fetchCatalog: (provider?: string, model?: string) => Promise<VoiceCatalog>;
}): React.ReactElement {
  const fetcher = useRef(fetchCatalog);
  fetcher.current = fetchCatalog;
  const [catalog, setCatalog] = useState<VoiceCatalog>({});
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    let alive = true;
    setLoading(true);
    setCatalog({});
    setError("");
    void fetcher
      .current(value.provider, value.model)
      .then((next) => {
        if (!alive) return;
        setCatalog(next);
        setError(next.error ? String(next.error) : "");
      })
      .catch((err) => {
        if (alive) setError(String(err?.message || err));
      })
      .finally(() => {
        if (alive) setLoading(false);
      });
    return () => {
      alive = false;
    };
  }, [value.provider, value.model]);
  const entries: any[] = Array.isArray(catalog.items)
    ? catalog.items
    : [
        ...(Array.isArray(catalog.profiles)
          ? catalog.profiles.map((item: any) => ({
              ...item,
              voice_kind: "profile",
            }))
          : []),
        ...(Array.isArray(catalog.voices)
          ? catalog.voices.map((item: any) => ({
              ...item,
              voice_kind: "voice",
            }))
          : []),
      ];
  const itemKey = (item: any) =>
    JSON.stringify([
      item.provider || "",
      item.model || "",
      item.voice_kind === "profile" ? "profile" : "voice",
      item.id,
    ]);
  const selected = entries.find(
    (item) =>
      item.id === (value.profile || value.voice) &&
      (item.voice_kind === "profile") === Boolean(value.profile) &&
      (!value.provider || !item.provider || item.provider === value.provider) &&
      (!value.model || !item.model || item.model === value.model),
  );
  const voiceKey = selected
    ? itemKey(selected)
    : value.profile || value.voice
      ? JSON.stringify([
          value.provider || "",
          value.model || "",
          value.profile ? "profile" : "voice",
          value.profile || value.voice,
        ])
      : "";
  const options = entries
    .filter(
      (item) =>
        item?.id &&
        (!value.provider || !item.provider || item.provider === value.provider),
    )
    .map((item) => ({
      value: itemKey(item),
      label: `${item.label || item.name || item.id}${!value.provider && item.provider ? ` · ${item.provider}` : ""}`,
    }));
  if (voiceKey && !options.some((item) => item.value === voiceKey))
    options.unshift({
      value: voiceKey,
      label: `${value.profile || value.voice} (saved)`,
    });
  const update = (patch: Partial<VoicePreferences>) =>
    onChange({ ...value, ...patch });
  return (
    <div className="af-voice-settings">
      <p>
        Speech is generated by your authenticated Gateway. Leave routing and
        voice unset to use its defaults.
      </p>
      <ProviderModelPicker
        value={{ provider: value.provider || "", model: value.model || "" }}
        onChange={(next) =>
          onChange({ ...value, ...next, voice: "", profile: "" })
        }
        fetchProviders={async () => {
          const next = await fetcher.current();
          if (next.error && !names(next.tts_providers || next.providers).length)
            throw new Error(next.error);
          return names(next.tts_providers || next.providers).map((name) => ({
            name,
          }));
        }}
        fetchModels={async (provider) => {
          const next = await fetcher.current(provider);
          return names(
            next.tts_models_by_provider?.[provider] ||
              next.tts_models ||
              next.models,
          );
        }}
        providerLabel="Speech provider"
        modelLabel="Speech model"
      />
      <label>
        Voice / profile
        <AfSelect
          ariaLabel="AI voice"
          placeholder="Gateway / provider default"
          value={voiceKey}
          disabled={loading}
          options={[
            { value: "", label: "Gateway / provider default" },
            ...options,
          ]}
          onChange={(key) => {
            if (!key) {
              update({ voice: "", profile: "" });
              return;
            }
            const [provider, model, kind, id] = JSON.parse(key);
            // A profile selection is a route selection too. Never combine an id
            // from one engine with the Gateway's default engine or a stale model.
            update({
              provider: provider || value.provider || "",
              model:
                model ||
                (provider && provider !== value.provider ? "" : value.model) ||
                "",
              voice: kind === "voice" ? id : "",
              profile: kind === "profile" ? id : "",
            });
          }}
        />
      </label>
      {loading ? <p role="status">Loading available voices…</p> : null}
      {error ? (
        <p role="alert">
          Voice discovery unavailable: {error}. Your saved choice is preserved.
        </p>
      ) : null}
      <label>
        Speaking speed
        <select
          aria-label="Speech speed"
          value={value.speed ?? ""}
          onChange={(event) =>
            update({
              speed: event.target.value
                ? Number(event.target.value)
                : undefined,
            })
          }
        >
          <option value="">Gateway default</option>
          {[0.5, 0.75, 1, 1.25, 1.5, 2].map((speed) => (
            <option key={speed} value={speed}>
              {speed}×
            </option>
          ))}
        </select>
      </label>
      {catalog.controls?.quality_preset?.supported ? (
        <label>
          Quality
          <select
            aria-label="Speech quality"
            value={value.quality_preset || ""}
            onChange={(event) => update({ quality_preset: event.target.value })}
          >
            <option value="">Gateway default</option>
            {names(catalog.controls.quality_preset.values).map((quality) => (
              <option key={quality} value={quality}>
                {quality}
              </option>
            ))}
          </select>
        </label>
      ) : null}
      {catalog.controls?.instructions?.supported ? (
        <label>
          Delivery instructions
          <textarea
            aria-label="Voice delivery instructions"
            rows={3}
            placeholder="For example: calm, clear, and conversational"
            value={value.instructions || ""}
            onChange={(event) => update({ instructions: event.target.value })}
          />
        </label>
      ) : null}
      <button type="button" onClick={() => onChange({})}>
        Reset to Gateway defaults
      </button>
    </div>
  );
}
